version: '3.8'

services:
  app:
    build: .
    container_name: soucissnote
    working_dir: /var/www
    ports:
      - "25565:9000"
    volumes:
      - app_storage:/var/www/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY:-base64:your_app_key_here}
      - APP_URL=${APP_URL:-http://localhost:25565}
    restart: unless-stopped

volumes:
  app_storage:
    driver: local
