version: '3'

services:
  app:
    image: soucissnote:latest
    container_name: soucissnote
    ports:
      - "25565:9000"
    volumes:
      - /mnt/datas/docker/soucissnote/storage:/var/www/storage
      - /mnt/datas/docker/soucissnote/bootstrap/cache:/var/www/bootstrap/cache
      - /mnt/datas/docker/soucissnote/database/database.sqlite:/var/www/database/database.sqlite
      - /mnt/datas/docker/soucissnote/.env:/var/www/.env
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY:-base64:your_app_key_here}
      - APP_URL=${APP_URL:-http://localhost:25565}
      - SERVER_PORT=9000
      - SERVER_HOST=0.0.0.0
    restart: unless-stopped
