CREATE TABLE Users(
   user_id INT AUTO_INCREMENT,
   email VARCHAR(255) NOT NULL,
   username VARCHAR(50) NOT NULL,
   password VARCHAR(255),
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   CONSTRAINT PK_Users PRIMARY KEY(user_id),
   CONSTRAINT UK_Users_email UNIQUE(email),
   CONSTRAINT UK_Users_username UNIQUE(username)
);
